"""Mock-interview module.

Two modes:

1. drill_question(vs, llm, topic=None)
     -> {"question": str, "ground_truth_context": str, "sources": [...]}
   The HR-style question is generated by the LLM from a randomly-picked Stellantis
   topic (or the one you specify), using retrieved context so it stays grounded.

2. grade_answer(question, user_answer, ground_truth_context, llm)
     -> {"score": int 0..10, "what_you_got_right": str, "what_you_missed": str,
         "model_answer": str, "follow_up": str}

Pure functions — UI code lives in app.py.
"""
from __future__ import annotations

import json
import random
import re
from typing import Any

from langchain.prompts import PromptTemplate

import config
from rag_chain import retrieve, _format_context, get_llm, _to_text


# ---------- Question generation ----------

QUESTION_GEN_PROMPT = PromptTemplate(
    input_variables=["topic_label", "context"],
    template="""You are an HR interviewer at Stellantis preparing to interview a candidate
for a CIFRE PhD position. Using ONLY the context below, write ONE realistic interview question
on the topic "{topic_label}". The question should:
- be open-ended (not yes/no),
- be answerable from the context (so a grader can check the candidate),
- sound natural (like a real HR / hiring-manager question, not a quiz),
- be one or two sentences only.

Return ONLY the question text. No preamble, no quotes.

Context:
{context}

Question:""",
)


def _seed_for_topic(topic_key: str) -> str:
    """Map our 11 topic keys to a short HR-friendly label."""
    return {
        "partners_labs_companies": "Stellantis' research partners and corporate alliances",
        "goals_short_mid_long_term": "Stellantis' strategic goals (Dare Forward 2030, electrification, carbon-neutral 2038)",
        "teams": "Stellantis' leadership and executive teams",
        "departments": "Stellantis' main business units / departments",
        "programs": "Stellantis' flagship programs (STLA platforms, Free2move, SDV, etc.)",
        "certifications": "Stellantis' certifications, ESG ratings, and audited standards",
        "agenda": "Stellantis' upcoming agenda (investor days, capital markets days, earnings)",
        "contributions": "Stellantis' societal and research contributions",
        "research_papers": "Stellantis' research publications and patents",
        "stocks": "Stellantis' share structure, listings, dividend and buyback policy",
        "press_releases": "Stellantis' recent press releases",
    }.get(topic_key, topic_key.replace("_", " "))


def drill_question(vs, llm=None, topic: str | None = None) -> dict[str, Any]:
    llm = llm or get_llm()
    if topic is None:
        topic = random.choice(list(config.INTERVIEW_TOPICS.keys()))
    seed_question = config.INTERVIEW_TOPICS[topic]
    docs = retrieve(seed_question, vs)
    context = _format_context(docs)
    prompt = QUESTION_GEN_PROMPT.format(topic_label=_seed_for_topic(topic), context=context)
    q = _to_text(llm.invoke(prompt)).strip().strip('"').strip()
    # Clip to the first non-empty paragraph just in case.
    q = q.split("\n\n")[0].strip()
    return {
        "topic": topic,
        "question": q,
        "ground_truth_context": context,
        "sources": [
            {"url": d.metadata.get("source", ""), "title": d.metadata.get("title", "")}
            for d in docs
        ],
    }


# ---------- Answer grading ----------

GRADE_PROMPT = PromptTemplate(
    input_variables=["question", "user_answer", "context"],
    template="""You are coaching a candidate for a CIFRE PhD interview at Stellantis.
Grade their answer against the source-of-truth context below.

Use ONLY the context to judge accuracy. If the candidate mentions a fact NOT in the context,
treat it as unverified (not wrong, just unverified).

Return STRICT JSON with this exact schema and nothing else:
{{
  "score": <integer 0..10>,
  "what_you_got_right": "<bullet list as a single string with '\\n- ' separators>",
  "what_you_missed": "<bullet list of important facts from the context that the candidate did NOT mention>",
  "model_answer": "<a concise, well-structured ideal answer (4-8 bullet points), grounded ONLY in the context>",
  "follow_up": "<one tougher follow-up question an HR could ask next, based on the context>"
}}

Question:
{question}

Candidate's answer:
{user_answer}

Context (source of truth):
{context}

JSON:""",
)


def _safe_json(text: str) -> dict[str, Any]:
    """LLMs occasionally wrap JSON in fences or trail tokens — extract the first object."""
    text = text.strip()
    # strip code fences if any
    text = re.sub(r"^```(?:json)?\s*", "", text)
    text = re.sub(r"\s*```$", "", text)
    # find the first balanced { ... }
    start = text.find("{")
    if start < 0:
        return {"score": 0, "what_you_got_right": "", "what_you_missed": "",
                "model_answer": text, "follow_up": ""}
    depth = 0
    for i in range(start, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                blob = text[start:i + 1]
                try:
                    return json.loads(blob)
                except json.JSONDecodeError:
                    break
    # last resort
    return {"score": 0, "what_you_got_right": "",
            "what_you_missed": "(parser could not read the LLM output)",
            "model_answer": text, "follow_up": ""}


def grade_answer(
    question: str,
    user_answer: str,
    ground_truth_context: str,
    llm=None,
) -> dict[str, Any]:
    llm = llm or get_llm()
    prompt = GRADE_PROMPT.format(
        question=question,
        user_answer=user_answer.strip() or "(no answer)",
        context=ground_truth_context,
    )
    raw = _to_text(llm.invoke(prompt))
    parsed = _safe_json(raw)
    # type-coerce score
    try:
        parsed["score"] = max(0, min(10, int(parsed.get("score", 0))))
    except (TypeError, ValueError):
        parsed["score"] = 0
    return parsed
